plugin: aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
  tag:Name: Terraform-Ansible-Instance
keyed_groups:
  - key: tags.Name
    prefix: tag
groups:
  web_servers: true
hostnames:
  - ip-address
